### ISSUE TITLE
Add production and development-* images.

### ISSUE THREAD

**Issue by envygeeks** [jekyll/docker-jekyll#13]
Production links to stable, development-* includes all packages for installing pretty much anything.

**Comment by jhabdas** [comment]
Given users might experience differences between prod and dev under this setup due to changes in dependencies installed and various dependency versions would it make more sense to provide a single "works on my machine" image for both environments and some kind of a kitchen sink version for tooling around?

**Comment by envygeeks** [comment]
Dependencies and their versions are up to and locked by you, not by us so even though this sounds mean that's not our concern.  Your logic is broken (at least to me) but your idea is right that we need to have a kitchensink image or probably just go ahead and keep gcc, g++ and a few *-dev libs available on all images (and this benefits me quite a bit for my own personal reasons) because we do now allow people to auto-install gems from their Gemfile which means we can create "what the *" moments when some C dependencies don't compile.  At the end of the day I think I'll close this image and just add a few stable system libs to the image so it doesn't grow too much but doesn't limit users.

**Comment by jhabdas** [comment]
Thanks for thinking it through!
